spring:
  application:
    name: "Travel"

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

api-key:
  kakao: "KakaoAK ff9c4ad26bc2db92ab2d0aa791d666f2"
  tourist: "7MHo3AEgYnMAKhbJdSBI2dtOjDUyB3UcsQFyA6KAUnw%2BaSVs57dY6OiQIAMuWRY4kLhrkfMxkVzVpOD%2FVnsUkg%3D%3D"


server:
  port: 8080
